name: NeoBot
main: dev.neovoxel.neobot.NeoBotBukkit
version: 0.2
author: NeoVoxelDev Team
description: A bot plugin that connects Minecraft with QQ, Kook, Discord, etc.
softdepend:
  - PlaceholderAPI
commands:
  neobot:
    description: NeoBot command
